---
name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "NOTICE"
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "NOTICE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: Run unit tests
        run: make tests
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
      - name: Dry-run release snapshot
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v0.169.0
          args: release --snapshot --skip-publish --rm-dist
